export const LESSONS = [
  {
    id: "welcome",
    title: "1. Del dato a la decisión",
    view: "dashboard",
    target: "kpis",
    body: "Empieza por el contexto: estos indicadores resumen {transactions} transacciones sintéticas. Cambia un filtro y observa cómo todas las medidas conservan una única definición.",
    question: "¿Por qué conviene centralizar la definición de un KPI?",
  },
  {
    id: "model",
    title: "2. Modelo estrella",
    view: "model",
    target: "model",
    body: "La tabla de hechos registra cada venta. Productos, clientes y eventos son dimensiones conectadas por relaciones uno a muchos. Selecciona una tabla para inspeccionar sus claves.",
    question: "¿Qué diferencia hay entre una tabla de hechos y una dimensión?",
  },
  {
    id: "quality",
    title: "3. Contrato y calidad",
    view: "data",
    target: "data-grid",
    body: "Antes de visualizar, el pipeline comprueba columnas obligatorias, IDs únicos, referencias y valores financieros. Un dashboard bonito con datos rotos sigue estando roto.",
    question: "¿Qué error detectaría una validación de claves foráneas?",
  },
  {
    id: "measures",
    title: "4. Medidas y filtros",
    view: "dashboard",
    target: "filters",
    body: "Los filtros cambian el contexto de evaluación. El margen mostrado es ponderado: utilidad total dividida por ingreso total, no el promedio simple de porcentajes.",
    question: "¿Por qué un margen ponderado puede diferir del promedio de márgenes?",
  },
  {
    id: "geography",
    title: "5. Lectura geográfica",
    view: "dashboard",
    target: "map",
    body: "El mapa agrega ventas por ciudad. Selecciona una burbuja para convertir la geografía en un filtro del reporte completo.",
    question: "¿Qué sesgo puede aparecer si comparas ciudades solo por ingreso?",
  },
  {
    id: "code",
    title: "6. Del Python al producto",
    view: "code",
    target: "code-viewer",
    body: "El visor muestra fragmentos del código real: generación, contrato, KPIs, build y tutor. La lógica se prueba fuera de la interfaz y luego se reutiliza.",
    question: "¿Qué ventaja aporta separar lógica analítica y presentación?",
  },
  {
    id: "ai",
    title: "7. IA con guardrails",
    view: "code",
    target: "tutor",
    body: "Gemini no controla el navegador libremente. Devuelve JSON estructurado con acciones permitidas y la aplicación valida destino y valor antes de ejecutarlas.",
    question: "¿Por qué una allowlist es más segura que ejecutar código generado?",
  },
  {
    id: "lab",
    title: "8. Tu propio experimento",
    view: "lab",
    target: "lab",
    body: "Genera otra muestra o carga un CSV sintético. El análisis ocurre en el navegador: las filas importadas no se envían al tutor Gemini.",
    question: "¿Qué campos mínimos necesita una tabla de ventas analizable?",
  },
];

export const QUICK_QUESTIONS = [
  "Explícame el modelo relacional",
  "¿Cómo se calcula el margen?",
  "Enséñame el mapa y cómo filtrarlo",
  "Muéstrame el código de los KPIs",
  "¿Cómo cargo mi propio CSV sintético?",
];
